.travis.yml
README.md
fastlane-plugin-sentry.gemspec
fastlane/Fastfile
fastlane/README.md
lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb
lib/fastlane/plugin/sentry/version.rb
spec/sentry_upload_dsym_spec.rb

Potentially fixes #2 (again)
`rest-client` seems to have a hard time with large file uploads. I was having uploading on of my dSYMs that was about 30MB 😱  I was getting timeouts but manually setting a higher timeout did not seem to do much of anything.
This change gives the option to manually set a timeout (which will get dropped into `rest-client`) but also gives an option to use `curl` instead of a `rest-client` which seems to behave better.
I did not make it default to `curl` yet since I like the more ruby approach (which is `rest-client`) but we may go to `curl` by default if it seems to work better after more experimentation 🚀

Added timeout and ability to use curl instead of restclient

---

lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb

Hey everyone! 🙂
Prior to these changes the code would incorrectly report that version 1.0.0
of the sentry-cli was less than the required version of 0.25.0. The issue
was that “1.0.0” was converted to 100 and “0.25.0” was converted to 250,
and thus comparing `sentry_cli_version` to `required_version` did not
give the expected result.
Leveraging `Gem::Version`s support for parsing and comparing versions
fixes the problem.

Fix incorrect comparison of sentry-cli version

---

.rubocop.yml
README.md
fastlane-plugin-sentry.gemspec
lib/fastlane/plugin/sentry/actions/sentry_create_release.rb
lib/fastlane/plugin/sentry/actions/sentry_finalize_release.rb
lib/fastlane/plugin/sentry/actions/sentry_upload_dsym.rb
lib/fastlane/plugin/sentry/actions/sentry_upload_file.rb
lib/fastlane/plugin/sentry/actions/sentry_upload_sourcemap.rb
lib/fastlane/plugin/sentry/helper/sentry_config.rb
lib/fastlane/plugin/sentry/helper/sentry_helper.rb
spec/sentry_config_spec.rb
spec/sentry_upload_dsym_spec.rb
spec/sentry_upload_file_spec.rb
spec/sentry_upload_sourcemap_spec.rb

With fastlane use in react-native apps, these tasks are needed to upload JS bundles and their sourcemaps to releases. This set of commits adds more of the CLI functionality to fastlane actions to avoid having to curl manually in a project's Fastfile.
- Refactor common code in preparation for new actions
- Add Rubocop configuration to ensure code style consistency between actions
- Add four new actions: `sentry_create_release`, `sentry_finalize_release`, `sentry_upload_file`, and `sentry_upload_sourcemap`. Each action has the same authentication param signature as the existing dsym action.
1. Run added rspec tests to test basic param handling and param validation.
2. In private project using Sentry and fastlane, replace existing curl commands with new Sentry plugin commands and run the …

Add actions for managing releases, files, and sourcemaps 

---

lib/fastlane/plugin/sentry/helper/sentry_config.rb

I think that `debug` is [a bit too much](https://github.com/getsentry/sentry-cli/issues/68) for when you're asking for verbose at Fastlane level
I also made it uppercase, because that's what the CLI recommends:
```sh
~/d/p/o/r/fastlane-plugin-sentry   master  sentry-cli --help                                                                                                                                                                                                                                                                            245ms  Mon 15 May 16:25:14 2017
sentry-cli 1.9.1
Command line utility for Sentry.
This tool helps you managing remote resources on a Sentry server like
sourcemaps, debug symbols, releases or similar.  Use `--help` on the
subcommands to learn more …
```

Use info instead of debug for verbose

---

lib/fastlane/plugin/sentry/actions/sentry_create_release.rb
lib/fastlane/plugin/sentry/actions/sentry_finalize_release.rb
lib/fastlane/plugin/sentry/actions/sentry_upload_file.rb
lib/fastlane/plugin/sentry/actions/sentry_upload_sourcemap.rb
spec/sentry_create_release_spec.rb
spec/sentry_upload_file_spec.rb
spec/sentry_upload_sourcemap_spec.rb

Resolves #22 
Summary:
Removes the default value for app_identifier so that users releases aren't affected.
Test Plan:
- Run the added tests.
- Test locally with app, ensure that previous version numbering scheme is maintained by default.

Remove default value from app_identifier argument

---

README.md
lib/fastlane/plugin/sentry/actions/sentry_upload_file.rb
lib/fastlane/plugin/sentry/actions/sentry_upload_sourcemap.rb
spec/sentry_upload_file_spec.rb
spec/sentry_upload_sourcemap_spec.rb

Copied from outdated PR:
Summary:
The dist argument addition made it so that users needed to add dist: false to their call to sentry_upload_file to match previous behavior, which isn't obvious at first glance. Without providing a value, the argument defaults to '' (empty string), which causes the CLI to prompt for the arg. The CLI has a separate bug in which it hangs if no text is entered in the prompt.
I think the best solution is this PR, which makes the fastlane plugin signature match the CLI signature of the dist arg being optional, which prevents users from having to provide false as a value to the string argument to prevent being prompted for a value.
CLI spec: https://github.com/getsentry/sentry-cli/blob/0dd8e59f1f38581a2d66de6f4666f29acfc236a7/src/commands/releases.rs#L165
Test …

Make dist parameter optional to match CLI behavior

---

lib/fastlane/plugin/sentry/actions/sentry_upload_sourcemap.rb

Mirror sentry-cli options for `--ignore` and `--ignore-file` for sentry_upload_sourcemap
Refs #52

feat: allow ignoring files when uploading sourcemaps

---

lib/fastlane/plugin/sentry/helper/sentry_helper.rb

`gets` will wait for more output to be produced if the stream is not
yet closed. Since only stdout is forwarded, it should be handled
before stderr, and logged to the user as it comes in. After the
command has finished, stderr is read and buffered to completion.

Log sentry-cli output while the command is still running

---

lib/fastlane/plugin/sentry/helper/sentry_config.rb

We have more than one Sentry project, and our Fastlane script makes sure to use the right slug each time.
Unfortunately it's not possible to do this _and_ fallback to `.sentryclirc` because right now we have an all-or-nothing solution which pairs auth config with org/project names.
This PR separates that into two separate checks, so it's possible to make a call like this:
```ruby
sentry_upload_dsym(
org_slug: 'my-org',
project_slug: 'my-project',
dsym_path: 'sexy-dsym-path'
)
```
And still use the auth token that's contained in the user's `.sentryclirc` file.

Allow falling back to .sentryclirc for auth only

---

.rubocop.yml

The rubocop.yml contained a few invalid configs. They are now updated
or removed.
The build was already failing on Travis. This is a first step towards fixing the build.

build: Fix Rubocop

---

lib/fastlane/plugin/sentry/actions/sentry_upload_sourcemap.rb

To harmonize with other actions, I propose to delete the version's escaping for `sentry_upload_sourcemaps`, which is causing some issues with the version number. 
This PR will resolve #57.

Remove version escaping in sentry_upload_sourcemaps

---

.github/workflows/test.yml

`travis-ci.org` is shutting down  and Sentry is migrating to GitHub Actions.

build(ci): Migrate to GitHub Actions

---

lib/fastlane/plugin/sentry/actions/sentry_create_release.rb
lib/fastlane/plugin/sentry/actions/sentry_finalize_release.rb
lib/fastlane/plugin/sentry/actions/sentry_set_commits.rb
lib/fastlane/plugin/sentry/actions/sentry_upload_file.rb
lib/fastlane/plugin/sentry/actions/sentry_upload_sourcemap.rb
spec/sentry_create_release_spec.rb
spec/sentry_set_commits_spec.rb
spec/sentry_upload_file_spec.rb
spec/sentry_upload_sourcemap_spec.rb

When creating Sentry releases through these actions, Sentry events would come through that wouldn't tie to those specific releases and would instead create a duplicate release. This is because Sentry expects an `@` between the app/bundle identifier and the version/build number instead of the `-` that is currently seperating the two.

fix: Align release name format with Sentry releases

---

lib/fastlane/plugin/sentry/version.rb

The [1.63.1](https://github.com/getsentry/sentry-cli/releases/tag/1.63.1) release for sentry-cli contains an important fix for processing dSYMS with BCSymbolMaps. Therefore we set the minimum sentry-cli version to 1.63.1.

fix: Fix bitcode processing with sentry-cli

---

README.md
lib/fastlane/plugin/sentry/actions/sentry_create_deploy.rb
spec/sentry_create_deploy_spec.rb

- Introduce `sentry_create_deploy` action.
- The `url` parameter of the `sentry-cli` command is named `deploy_url` in the action, as it collides with another param.
- Created `rspec` tests similar to other actions, mainly testing the parameters and how they translate to `sentry-cli` parameters.
- Tested with an iOS application that has sentry setup and created deploys with the param combinations. Could not see more info for deploys in `senty.io` though, is this a permissions/account "issue"?
Relates to #82

feat: Sentry Create Deploy Action

---

lib/fastlane/plugin/sentry/helper/sentry_config.rb

To help troubleshoot things (including: https://github.com/getsentry/sentry-fastlane-plugin/issues/39)
`--verbose` should equal to `SENTRY_LOG_LEVEL=DEBUG`

print sentry-cli level debug when verbose is set

---

.github/workflows/danger.yml
CHANGELOG.md
dangerfile.js

This PR adds the friendly Danger to ensure new fixes and features get properly registered on the changelog.
Validated here: https://github.com/lucas-zimerman/sentry-fastlane-plugin/pull/1
#skip-changelog.

Feat: Add Danger

---

CHANGELOG.md
README.md
lib/fastlane/plugin/sentry/actions/sentry_create_deploy.rb
lib/fastlane/plugin/sentry/actions/sentry_create_release.rb
lib/fastlane/plugin/sentry/actions/sentry_finalize_release.rb
lib/fastlane/plugin/sentry/actions/sentry_set_commits.rb
lib/fastlane/plugin/sentry/actions/sentry_upload_file.rb
lib/fastlane/plugin/sentry/actions/sentry_upload_sourcemap.rb
spec/sentry_create_deploy_spec.rb
spec/sentry_finalize_release_spec.rb
spec/sentry_set_commits_spec.rb
spec/sentry_upload_file_spec.rb
spec/sentry_upload_sourcemap_spec.rb

- Adds `build` parameter for actions that also take `version` and `app_identifier`
- Build is appended to previous version string, superseded by a `+` character: `app_identifier@version+build`
Closes #84

feat: Support build numbers in versions

---

CHANGELOG.md
README.md
lib/fastlane/plugin/sentry/actions/sentry_upload_dif.rb
spec/sentry_upload_dif_spec.rb

- Introduce `sentry_upload_dif` action.
- Created `rspec` tests, testing the parameters and how they translate to `sentry-cli` parameters.
- Tested with an iOS application that has sentry setup to upload dsym files using `upload-dif` action.
Relates to #86

feat: Add sentry-cli upload-dif action

---

CHANGELOG.md
lib/fastlane/plugin/sentry/actions/sentry_upload_sourcemap.rb
spec/sentry_upload_sourcemap_spec.rb

```
--strip-common-prefix
Similar to --strip-prefix but strips the most common prefix on all sources references.
--strip-prefix <PREFIX>...
Strips the given prefix from all sources references inside the upload sourcemaps (paths
used within the sourcemap content, to map minified code to it's original source). Only
sources that start with the given prefix will be stripped.
This will not modify the uploaded sources paths. To do that, point the upload or upload-
sourcemaps command to a more precise directory instead.
```
A regression occurred here - https://github.com/getsentry/sentry-fastlane-plugin/commit/1ca8217d8b1283efc6a3d34cead6fbc4db52de65 where it assumed that `--strip-common-prefix` acts like `--strip-prefix`, but it does not. It is a flag that is either included or not. It does not …

fix: (upload-sourcemaps) - don't push value to non-value param

---

CHANGELOG.md
README.md
lib/fastlane/plugin/sentry/actions/sentry_check_cli_installed.rb
spec/sentry_check_cli_installed_spec.rb

Added a new action which will only pass if the sentry-cli is installed and meets the minimum version.
This is intended to be used at the start of the lane to ensure the machine is setup correctly before preceding to build and upload the app. This avoids long waits just to see that the Sentry upload will fail later on, which might leave some builds being uploaded to the App Store without source maps also being uploaded.

feat: Add an action to check sentry-cli is installed

---

CHANGELOG.md
lib/fastlane/plugin/sentry/version.rb

Bump minimum sentry-cli version to 1.72.0,
because of an important bug fix that sometimes
crashed the upload process,
https://github.com/getsentry/sentry-cli/pull/1104.
Fixes GH-108

fix: Bug in upload process

---

README.md

GH-97 added the possibility to pass a custom sentry-cli path to
every action, but the PR didn't add docs. This PR adds the
missing docs.

docs: Add docs for sentry-cli-path

---

.github/workflows/integration-test.yml
.github/workflows/test.yml
fastlane-plugin-sentry.gemspec
fastlane/Fastfile
integration.sh
script/integration-test-server.py

This PR adds an integration test for `upload-diff` action.
- Action is called through a fastlane `lane`
- A mock server returning expected values for `sentry-cli` calls
- Taken from https://github.com/getsentry/sentry-unity/pull/763
- Bumps required ruby version to `2.6.0`
- Test action required this

Enha: upload-dif integration test

---

CHANGELOG.md
lib/fastlane/plugin/sentry/helper/sentry_helper.rb

NOTE: This will return concatenated stdout and stderr, but for our use case it's okay (see the reasoning in the comment).
However, It would be best to rewrite it in the future to use `popen3` and threads or `IO.select` to allow for non-blocking buffer reads, and here returns `stdout` only. I don't know ruby well enough to do it swiftly, so I'll leave it to someone else.
Fixes https://github.com/getsentry/sentry-fastlane-plugin/issues/139

fix: Return output from call_sentry_cli

---

CHANGELOG.md
README.md
lib/fastlane/plugin/sentry/actions/sentry_upload_sourcemap.rb
spec/sentry_upload_sourcemap_spec.rb

Closes #141 
Thanks for the plugin! I noticed the same issue as in #141 and would like to drop our custom shell script step, so here's a quick enhancement for that. I'm a Ruby-noob so let me know if something here should be done differently.
Some cases, such as when using Hermes builds with React Native on Android, require uploading both the bundle file and its corresponding source map simultaneously to be correctly processed by Sentry.
To avoid breaking backwards compatbility, use the same singular argument name but accept both string and array values.

Enha: Support uploading multiple source map files simultaneously

---

.github/workflows/integration-test.yml
CHANGELOG.md
bin/sentry_cli_path
fastlane-plugin-sentry.gemspec
script/sentry-cli-download.sh

Closes https://github.com/getsentry/sentry-fastlane-plugin/issues/161

Fix: Bundle correct sentry-cli os/arch

---

CHANGELOG.md
README.md
lib/fastlane/plugin/sentry/actions/sentry_upload_dif.rb
spec/sentry_upload_dif_spec.rb

Closes #162 
Add the possibility to provide multiple paths to the `upload-dif` command.
https://docs.sentry.io/product/cli/dif/#uploading-files

Support multiple paths in `upload_dif` command

---

.github/workflows/test.yml

Replace deprecated actions/setup-ruby@v1 with ruby/setup-ruby@v1.

ci: Remove deprecated setup-ruby action

---

CHANGELOG.md
README.md
lib/fastlane/plugin/sentry/actions/sentry_set_commits.rb
spec/sentry_set_commits_spec.rb

New feature
1. Updated sentry_set_commits to support --ignore missing.
This PR resolves #179.

Updated sentry_set_commits

---

README.md

For Hermes bundle and map has to be uploaded together, otherwise, symbolication won't work.
- https://github.com/getsentry/sentry-react-native/issues/3061

Update RN Example to work with Hermes

---

test/integration-test-server.py

An API URL from sentry-cli includes the app identifier. This missing app identifier leads to failing integration tests. This is fixed now.

test: Fix integration test server

---

CHANGELOG.md
lib/fastlane/plugin/sentry/actions/sentry_upload_dif.rb
spec/sentry_upload_dif_spec.rb

We're just checking whether `include_source` is nil or not in order to pass the argument to sentry-cli.
Fixing this and checking whether `include_source` is true
close #227

fix: Don't upload code source if "include_source" is false

---

.github/workflows/prepare_release.yml

The `getsentry-release` is a GitHub bot account that is used in various automation, and the `${{ secrets.GH_RELEASE_PAT }}` is a personal access token from that bot account. We are using a regular GitHub account as a bot while it should be a non-human account since there are no humans behind it. Hence, we are replacing it with a GitHub App. 
Functionality wise, there will be no difference. 
More details: https://www.notion.so/sentry/DACI-Replace-GitHub-bot-accounts-with-GitHub-Apps-getsentry-release-15109965d1204a91b9be71c49e8b66e0?pvs=4

feat(release): Replace release bot with GH app

---

LICENSE

Related Cocoa PR https://github.com/getsentry/sentry-cocoa/pull/4702.

Update LICENSE date range to 2025

---

.github/workflows/CODEOWNERS

We don't need two Codeowners files. One is enough.

chore: Remove workflows Codeowners file

---

.github/workflows/add-platform-label.yml

replaces usage of GH platform label to Linear-compatible labels

chore(gh): Update add-platform-label.yml

---

CHANGELOG.md
README.md
lib/fastlane/plugin/sentry/actions/sentry_upload_mobile_app.rb
spec/sentry_upload_mobile_app_spec.rb

This calls `sentry-cli mobile-app upload` with a path to the xcarchive.
The lane looks like this (also documented in README):
```
sentry_upload_mobile_app(
api_key: '...', # Do not use if using auth_token
auth_token: '...', # Do not use if using api_key
org_slug: '...',
project_slug: '...',
xcarchive_path: './build/MyApp.xcarchive', # Path to your .xcarchive file
)
```
The `xcarchive_path` is automatically inferred from `SharedValue::XCODEBUILD_ARCHIVE` and can be overridden.
See this internal doc for more details on the implementation of this feature: https://www.notion.so/sentry/1f68b10e4b5d80b1a127fb174f87c555

feat(size-analysis): Add functionality and tests for iOS mobile app upload
